### ISSUE TITLE
trep headers not being properly installed

### ISSUE THREAD

**Issue by jarvisschultz** [MurpheyLab/trep#31]
On master branch right now (167141bfb8046e0ec8d2b4f13e7c5ae93f3c6252), the headers are not being installed correctly. I'm guessing that defaulting to `setuptools` instead of `distutils` ([Lines 3-8](https://github.com/MurpheyLab/trep/blob/167141bfb8046e0ec8d2b4f13e7c5ae93f3c6252/setup.py#L3-L8)) is somehow causing the `install_headers` key in `cmd_options` to be ignored.

This causes problems when trying to compile external libraries that depend on `trep`.

**Comment by jarvisschultz** [comment]
It seems that `setuptools` always ignores the `install_headers` target. Setting the `--root` or `--single-version-externally-managed` forces `setuptools` to run this target. [This post](http://comments.gmane.org/gmane.comp.python.distutils.devel/12678) on the distutils mailing list helped describe this.

Forcing users to run `sudo python setup.py install_headers` as part of the install process would be an option around this. Alternatively, we could override the default command that `setuptools` uses (see [this page](http://www.niteoweb.com/blog/setuptools-run-custom-code-during-install)).

**Comment by adwilson10** [comment]
Another option is to package the header files into the dist and provide a function such as `trep.get_include()` which can be used by extension packages.  This seems to be how `numpy` handles it and would ensure that the headers are present independent of the installation method.

**Comment by adwilson10** [comment]
This should be resolved with 9f621b7c9363c36b9ea2afc5400344e8d7c04ed9.  A new function`trep.get_include()` should be used when building against the `trep` headers.
