### ISSUE TITLE
update Python package structure to work with latest catkin release

### ISSUE THREAD

**Issue by dirk-thomas** [MurpheyLab/trep#33]
Based on our discussion in ros/catkin#756 I wanted to fill this ticket. I am sorry for the inconvenience. Please update the package structure accordingly and release a new version in order to address the regression in Indigo (http://www.ros.org/debbuild/indigo.html?q=python_trep).

**Comment by adwilson10** [comment]
This should be resolved with 1017dc3a91a2a3f0bce63ae3a2e0fbb34eb78944 and released as v1.0.2.
